# Generated by Django 5.1.3 on 2024-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('p', 'Python')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('d', 'Django'), ('e', 'Express'), ('f', 'Flask')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontEndLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'CSS'), ('h', 'HTML'), ('j', 'JavaScript')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibrariesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(blank=True, choices=[('a', 'API'), ('b', 'Behave'), ('bs', 'Beautiful Soup'), ('g', 'Gherkins'), ('nj', 'Node JS'), ('p', 'Pymongo'), ('pg', 'PostgreSQL'), ('s', 'Selenium'), ('sn', 'Sinon'), ('sa', 'SQLAlchemy')], max_length=2, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=300)),
                ('have_website', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('both', 'Both')], default='no', max_length=4)),
                ('website_url', models.URLField(max_length=255)),
                ('github_url', models.URLField(max_length=255)),
                ('progress_status', models.CharField(choices=[('ip', 'In progress'), ('c', 'Completed')], default='ip', max_length=2)),
                ('created_on', models.DateTimeField(blank=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('backend_lang', models.ManyToManyField(blank=True, to='project.backendlanguagemodel')),
                ('framework', models.ManyToManyField(blank=True, to='project.frameworkmodel')),
                ('frontend_lang', models.ManyToManyField(blank=True, to='project.frontendlanguagemodel')),
                ('libraries', models.ManyToManyField(blank=True, to='project.librariesmodel')),
            ],
        ),
    ]
