# Generated by Django 5.1.3 on 2024-11-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_backendlanguagemodel_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='modified_at',
            new_name='modified_on',
        ),
        migrations.AlterField(
            model_name='librariesmodel',
            name='library',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
