# Generated by Django 5.1.3 on 2024-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_librariesmodel_librarymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backendlanguagemodel',
            options={'verbose_name': 'BackendLanguageModel', 'verbose_name_plural': 'BackendLanguagesModel'},
        ),
        migrations.AlterModelOptions(
            name='frameworkmodel',
            options={'verbose_name': 'FrameworkModel', 'verbose_name_plural': 'FrameworksModel'},
        ),
        migrations.AlterModelOptions(
            name='frontendlanguagemodel',
            options={'verbose_name': 'FrontEndLanguageModel', 'verbose_name_plural': 'FrontEndLanguagesModel'},
        ),
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': 'ProjectModel', 'verbose_name_plural': 'ProjectsModel'},
        ),
        migrations.AlterField(
            model_name='backendlanguagemodel',
            name='language',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='frameworkmodel',
            name='framework',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='frontendlanguagemodel',
            name='language',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='librarymodel',
            name='library',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
