# Generated by Django 5.1.3 on 2024-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_backendlanguagemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
