# Generated by Django 5.1.3 on 2024-11-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectmodel_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='have_website',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
