# Generated by Django 5.1.3 on 2024-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projectmodel_have_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='backend_lang',
            field=models.ManyToManyField(blank=True, related_name='backend_projects', to='project.backendlanguagemodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='framework',
            field=models.ManyToManyField(blank=True, related_name='framework_projects', to='project.frameworkmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='frontend_lang',
            field=models.ManyToManyField(blank=True, related_name='frontend_projects', to='project.frontendlanguagemodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='libraries_projects', to='project.librarymodel'),
        ),
    ]
