# Generated by Django 5.1.3 on 2024-11-29 15:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='about',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='About me'),
        ),
    ]
